<a href="https://www.kaggle.com/code/luxmikant2254/notebookcdb654e3e2?scriptVersionId=165754875" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/yolov8anprusingeasyocr/data.yaml
/kaggle/input/yolov8anprusingeasyocr/vita.mp4
/kaggle/input/yolov8anprusingeasyocr/test2.mp4
/kaggle/input/yolov8anprusingeasyocr/yolov8n.pt
/kaggle/input/yolov8anprusingeasyocr/Screenshot 2024-03-06 231803.png


In [2]:
!pip install ultralytics==8.0.0

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.0/117.0 kB 5.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... - done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 219.8/219.8 kB 12.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.5/154.5 kB 10.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 5.0 MB/s eta 0:00:00
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.9.3-py3-none-any.whl size=144554 sha256=f8d594c62f79ff126887539a379f96b87f7cf86d9d3b0e517423d87a36fad3eb
  Stored in directory: /root/.cache/pip/wheels/12/93/dd/1f6a127edc45659556564c5730f6d4e300888f4bca2d4c5a88
Successfully built antlr4-python3-runtime


In [3]:
!git clone https://github.com/AarohiSingla/Automatic-Number-Plate-Recognition--ANPR-.git
    

Cloning into 'Automatic-Number-Plate-Recognition--ANPR-'...
remote: Enumerating objects: 238, done.
remote: Counting objects: 100% (238/238), done.
remote: Compressing objects: 100% (210/210), done.
remote: Total 238 (delta 36), reused 215 (delta 21), pack-reused 0
Receiving objects: 100% (238/238), 12.63 MiB | 8.61 MiB/s, done.
Resolving deltas: 100% (36/36), done.


In [4]:
cd//kaggle/working/Automatic-Number-Plate-Recognition--ANPR-

/kaggle/working/Automatic-Number-Plate-Recognition--ANPR-


In [5]:
from ultralytics import YOLO
model = YOLO('/kaggle/input/yolov8anprusingeasyocr/yolov8n.pt')
# # Train the model with 2 GPUs
results = model.train(data='/kaggle/input/yolov8anprusingeasyocr/data.yaml', epochs=200, imgsz=640)

yolo/engine/trainer: task=detect, mode=train, model=yolov8n.yaml, data=/kaggle/input/yolov8anprusingeasyocr/data.yaml, epochs=200, patience=50, batch=16, imgsz=640, save=True, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=False, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, overlap_mask=True, mask_ratio=4, dropout=False, val=True, save_json=False, save_hybrid=False, conf=0.001, iou=0.7, max_det=300, half=True, dnn=False, plots=True, source=ultralytics/assets/, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, retina_masks=False, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.001, 

In [6]:
model = YOLO('/kaggle/working/Automatic-Number-Plate-Recognition--ANPR-/ultralytics/runs/detect/train_model/weights/best.pt')

In [7]:

model.predict('/kaggle/input/yolov8anprusingeasyocr/vita.mp4', save=True, imgsz=320, conf=0.2)

Ultralytics YOLOv8.0.3 🚀 Python-3.10.13 torch-2.1.2 CUDA:0 (Tesla T4, 15102MiB)
Fusing layers... 
Model summary: 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs
WARNING ⚠️ NMS time limit 0.550s exceeded
video 1/1 (1/665) /kaggle/input/yolov8anprusingeasyocr/vita.mp4: 192x320 1 licence, 190.3ms
video 1/1 (2/665) /kaggle/input/yolov8anprusingeasyocr/vita.mp4: 192x320 1 licence, 7.9ms
video 1/1 (3/665) /kaggle/input/yolov8anprusingeasyocr/vita.mp4: 192x320 1 licence, 6.9ms
video 1/1 (4/665) /kaggle/input/yolov8anprusingeasyocr/vita.mp4: 192x320 1 licence, 7.1ms
video 1/1 (5/665) /kaggle/input/yolov8anprusingeasyocr/vita.mp4: 192x320 1 licence, 6.8ms
video 1/1 (6/665) /kaggle/input/yolov8anprusingeasyocr/vita.mp4: 192x320 1 licence, 6.9ms
video 1/1 (7/665) /kaggle/input/yolov8anprusingeasyocr/vita.mp4: 192x320 1 licence, 6.8ms
video 1/1 (8/665) /kaggle/input/yolov8anprusingeasyocr/vita.mp4: 192x320 6.9ms
video 1/1 (9/665) /kaggle/input/yolov8anprusingeasyocr/vita.mp4: 192x320 7.1ms

[tensor([[5.09000e+02, 2.64000e+02, 6.58000e+02, 3.56000e+02, 4.82422e-01, 0.00000e+00]], device='cuda:0'),
 tensor([[5.10000e+02, 2.66000e+02, 6.59000e+02, 3.56000e+02, 5.05859e-01, 0.00000e+00]], device='cuda:0'),
 tensor([[5.11000e+02, 2.66000e+02, 6.59000e+02, 3.56000e+02, 4.84375e-01, 0.00000e+00]], device='cuda:0'),
 tensor([[5.10000e+02, 2.68000e+02, 6.59000e+02, 3.56000e+02, 4.32129e-01, 0.00000e+00]], device='cuda:0'),
 tensor([[5.11000e+02, 2.66000e+02, 6.56000e+02, 3.55000e+02, 3.52295e-01, 0.00000e+00]], device='cuda:0'),
 tensor([[5.09000e+02, 2.64000e+02, 6.58000e+02, 3.54000e+02, 3.61084e-01, 0.00000e+00]], device='cuda:0'),
 tensor([[5.10000e+02, 2.66000e+02, 6.58000e+02, 3.54000e+02, 3.01514e-01, 0.00000e+00]], device='cuda:0'),
 tensor([], device='cuda:0', size=(0, 6)),
 tensor([], device='cuda:0', size=(0, 6)),
 tensor([], device='cuda:0', size=(0, 6)),
 tensor([], device='cuda:0', size=(0, 6)),
 tensor([], device='cuda:0', size=(0, 6)),
 tensor([], device='cuda:0', 

In [8]:
!pip install easyocr

In [9]:
!python /kaggle/working/Automatic-Number-Plate-Recognition--ANPR-/predict_modified.py model='/kaggle/working/Automatic-Number-Plate-Recognition--ANPR-/ultralytics/runs/detect/train_model/weights/best.pt' source='/kaggle/input/yolov8anprusingeasyocr/vita.mp4'

2024-03-06 18:18:24.720079: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-06 18:18:24.720134: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-06 18:18:24.721489: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
Ultralytics YOLOv8.0.3 🚀 Python-3.10.13 torch-2.1.2 CUDA:0 (Tesla T4, 15102MiB)
Fusing layers... 
Model summary: 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs
video 1/1 (1/665) /kaggle/input/yolov8anprusingeasyocr/vita.mp4: 384x640 2 licences, 84.1ms
video 1/1 (2/665) /kaggle/input/yolov8anprusingeasyocr/vita.mp4: 384x640 2 licences, 10.2ms
video 1/1 (3

In [10]:

model.predict('/kaggle/input/yolov8anprusingeasyocr/test2.mp4', save=True, imgsz=320, conf=0.2)

Ultralytics YOLOv8.0.3 🚀 Python-3.10.13 torch-2.1.2 CUDA:0 (Tesla T4, 15102MiB)
Fusing layers... 
Model summary: 168 layers, 3005843 parameters, 0 gradients
video 1/1 (1/107) /kaggle/input/yolov8anprusingeasyocr/test2.mp4: 320x192 1 licence, 166.1ms
video 1/1 (2/107) /kaggle/input/yolov8anprusingeasyocr/test2.mp4: 320x192 1 licence, 7.0ms
video 1/1 (3/107) /kaggle/input/yolov8anprusingeasyocr/test2.mp4: 320x192 1 licence, 7.0ms
video 1/1 (4/107) /kaggle/input/yolov8anprusingeasyocr/test2.mp4: 320x192 1 licence, 7.1ms
video 1/1 (5/107) /kaggle/input/yolov8anprusingeasyocr/test2.mp4: 320x192 1 licence, 6.7ms
video 1/1 (6/107) /kaggle/input/yolov8anprusingeasyocr/test2.mp4: 320x192 1 licence, 6.5ms
video 1/1 (7/107) /kaggle/input/yolov8anprusingeasyocr/test2.mp4: 320x192 1 licence, 6.9ms
video 1/1 (8/107) /kaggle/input/yolov8anprusingeasyocr/test2.mp4: 320x192 1 licence, 6.7ms
video 1/1 (9/107) /kaggle/input/yolov8anprusingeasyocr/test2.mp4: 320x192 6.8ms
video 1/1 (10/107) /kaggle/input/

[tensor([[2.52000e+02, 4.78000e+02, 4.20000e+02, 5.81000e+02, 5.27344e-01, 0.00000e+00]], device='cuda:0'),
 tensor([[255.00000, 473.00000, 423.00000, 581.00000,   0.66357,   0.00000]], device='cuda:0'),
 tensor([[257.00000, 470.00000, 423.00000, 582.00000,   0.60010,   0.00000]], device='cuda:0'),
 tensor([[2.57000e+02, 4.69000e+02, 4.22000e+02, 5.82000e+02, 4.74609e-01, 0.00000e+00]], device='cuda:0'),
 tensor([[2.59000e+02, 4.69000e+02, 4.23000e+02, 5.80000e+02, 5.13672e-01, 0.00000e+00]], device='cuda:0'),
 tensor([[2.77000e+02, 4.97000e+02, 4.39000e+02, 5.88000e+02, 2.71240e-01, 0.00000e+00]], device='cuda:0'),
 tensor([[2.80000e+02, 4.94000e+02, 4.40000e+02, 5.91000e+02, 4.68750e-01, 0.00000e+00]], device='cuda:0'),
 tensor([[2.80000e+02, 4.68000e+02, 4.40000e+02, 5.96000e+02, 2.67334e-01, 0.00000e+00]], device='cuda:0'),
 tensor([], device='cuda:0', size=(0, 6)),
 tensor([[2.83000e+02, 4.99000e+02, 4.40000e+02, 5.95000e+02, 2.39380e-01, 0.00000e+00]], device='cuda:0'),
 tensor([

In [11]:
!python /kaggle/working/Automatic-Number-Plate-Recognition--ANPR-/predict_modified.py model='/kaggle/working/Automatic-Number-Plate-Recognition--ANPR-/ultralytics/runs/detect/train_model/weights/best.pt' source='/kaggle/input/yolov8anprusingeasyocr/test2.mp4'

2024-03-06 18:19:38.280729: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-06 18:19:38.280792: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-06 18:19:38.282222: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
Ultralytics YOLOv8.0.3 🚀 Python-3.10.13 torch-2.1.2 CUDA:0 (Tesla T4, 15102MiB)
Fusing layers... 
Model summary: 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs
video 1/1 (1/107) /kaggle/input/yolov8anprusingeasyocr/test2.mp4: 640x384 1 licence, 68.9ms
video 1/1 (2/107) /kaggle/input/yolov8anprusingeasyocr/test2.mp4: 640x384 1 licence, 6.3ms
video 1/1 (3/

In [12]:

model.predict('/kaggle/input/yolov8anprusingeasyocr/Screenshot 2024-03-06 231803.png', save=True, imgsz=320, conf=0.2)
!python /kaggle/working/Automatic-Number-Plate-Recognition--ANPR-/predict_modified.py model='/kaggle/working/Automatic-Number-Plate-Recognition--ANPR-/ultralytics/runs/detect/train_model/weights/best.pt' source='/kaggle/input/yolov8anprusingeasyocr/Screenshot 2024-03-06 231803.png'

Ultralytics YOLOv8.0.3 🚀 Python-3.10.13 torch-2.1.2 CUDA:0 (Tesla T4, 15102MiB)
Fusing layers... 
Model summary: 168 layers, 3005843 parameters, 0 gradients
image 1/1 /kaggle/input/yolov8anprusingeasyocr/Screenshot 2024-03-06 231803.png: 320x192 1 licence, 8.0ms
Speed: 0.3ms pre-process, 8.0ms inference, 2.3ms postprocess per image at shape (1, 3, 320, 320)
Results saved to runs/detect/predict3


2024-03-06 18:20:03.528479: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-06 18:20:03.528538: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-06 18:20:03.530186: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
Ultralytics YOLOv8.0.3 🚀 Python-3.10.13 torch-2.1.2 CUDA:0 (Tesla T4, 15102MiB)
Fusing layers... 
Model summary: 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs
image 1/1 /kaggle/input/yolov8anprusingeasyocr/Screenshot 2024-03-06 231803.png: 640x384 1 licence, 68.4ms
Speed: 0.4ms pre-process, 68.4ms inference, 562.3ms postprocess per image at shape (1, 3,

In [13]:
!python /kaggle/working/Automatic-Number-Plate-Recognition--ANPR-/predict_modified.py model='/kaggle/working/Automatic-Number-Plate-Recognition--ANPR-/ultralytics/runs/detect/train_model/weights/best.pt' source='/kaggle/input/yolov8anprusingeasyocr/test2.mp4'

2024-03-06 18:20:20.384088: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-06 18:20:20.384146: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-06 18:20:20.385457: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
Ultralytics YOLOv8.0.3 🚀 Python-3.10.13 torch-2.1.2 CUDA:0 (Tesla T4, 15102MiB)
Fusing layers... 
Model summary: 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs
video 1/1 (1/107) /kaggle/input/yolov8anprusingeasyocr/test2.mp4: 640x384 1 licence, 70.5ms
video 1/1 (2/107) /kaggle/input/yolov8anprusingeasyocr/test2.mp4: 640x384 1 licence, 6.1ms
video 1/1 (3/